#!/bin/sh
mount -t proc proc /proc
mount -o remount,rw /
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /bin/mdev > /proc/sys/kernel/hotplug

hostname $(cat /etc/hostname)
TZ=$(cat /etc/TZ) export TZ

if test -e /etc/kmap
then
	loadkmap < /kmap/$(cat /etc/kmap).kmap
else
	sh /etc/selectkmap.sh
	loadkmap < /kmap/$(cat /etc/kmap).kmap
fi

ifconfig lo 127.0.0.1 up
route add 127.0.0.1 lo
